### PR TITLE
Feature/quarkus 3.x

### PR DESCRIPTION
**Pull request by appiepollo14**
Start at updating Quarkus to 3.x  related to https://github.com/MicroShed/microshed-testing/issues/261

### CODE REVIEW

**Comment by appiepollo14** [comment]
@KyleAure what are your thoughts on the following: Quarkus 3.x relies on jakarta not javax. Injecting the org.microshed.testing.jaxrs.RESTClient failes as that one still relies on the javax package. As we use the transformer to transform javax to jakarta, how to make quarkus extension rely on that jakarta package? In my opinion MicroShould 1.0 shouldn't provide any Quarkus 1.0 javax support, that's rather old in the meantime.

**Comment by KyleAure** [comment]
We now produce two different artifacts. One that uses Javax and one that uses Jakarta. To use Jakarta you will have to include 'microshed-testing-core-jakarta' instead of 'microshed-testing-core'

I also duplicated the everything app so we have a Javax and Jakarta version for testing so no need to switch the imports in the everything app just switch to the Jakarta version.

**Comment by appiepollo14** [comment]
@KyleAure now I 'suffer' the consequences of working with two artifacts, I want to get back on my point about javax/jakarta. I don't thinks it's logical to continue this road. Lot's of other projects don't deliver two artifacts in the way we've now designed. They just switch within the same artifact, at a certain version from javax to jakarta. As we're still in a pre-release version, why don't we just focus on switching completely to jakarta and produce only one core artifact, just the microshed-testing-core which will be jakarta based starting from version 0.9.2. Please let's make our lives less complicated when going that route.

**Comment by appiepollo14** [comment]
@KyleAure another question. When switching in the Quarkus app in maven pom.xml to: 
`    <dependency>
      <groupId>org.microshed</groupId>
      <artifactId>microshed-testing-core-jakarta</artifactId>
      <version>0.9.2-SNAPSHOT</version>
      <scope>test</scope>
    </dependency>`
    
I get an error locally, dependency not found. The CI fails with the same reason: Failed to execute goal on project quarkus-demo: Could not resolve dependencies for project org.acme:quarkus-demo:jar:1.0.0-SNAPSHOT: Could not find artifact org.microshed:microshed-testing-core-jakarta:jar:0.9.2-SNAPSHOT 

How to resolve this dependency? Do I need to change something in the build.gradle for the jakarta core to resolve this issue?

**Comment by appiepollo14** [comment]
@KyleAure added publishToMavenLocal task for Jakarta core in testcontainers module to solve issue.

**Comment by appiepollo14** [comment]
@KyleAure RestAssured test in Quarkus sample app also fails because of: `PersonResourceTest.testGetPerson:59 » NoSuchMethod 'javax.json.bind.JsonbBuilder org.eclipse.yasson.JsonBindingProvider.create()'` There must be a workaround to solve this as otherwise no RestAssured tests can be uses. Might be as simple as providing javax jsonb somewhere in a module. Create a separate issue for this?

**Comment by KyleAure** [comment]
Sadly I don't think there is a resolution to this right now.  Rest-Assured would have to be updated to use the Jakarta versions of JSON-B.
It looks like you are already active on this issue: https://github.com/rest-assured/rest-assured/issues/1651

**Comment by appiepollo14** [comment]
@KyleAure true that's what I've been working on but can't succeed. Can you provide me an answer on how to deal work the two core modules. jakarta and javax. IMO we create one core module, from now on supporting jakarta. I think life will be much easier if we choose that route.

**Comment by KyleAure** [comment]
> Can you provide me an answer on how to deal work the two core modules. jakarta and javax. IMO we create one core module, from now on supporting jakarta. I think life will be much easier if we choose that route.

If you need a core module with the jakarta namespace then include the dependency `microshed-testing-core-jakarta`
If you need a core module with the javax namespace then include the dependency `microshed-testing-core`
It is as simple as that.

I modeled this after how Arquillian handles supporting both javax and jakarta namespaces.
I understand that it would be easier to just cut javax, but most application servers still support Java EE specifications. 
I want to make sure we have a pathway for someone who still has applications that was written for Java EE to be able to use Microshed Testing.

**Comment by appiepollo14** [comment]
@KyleAure they still can by keep using the 0.9.x version. We can provide bugfixes for that version and release new features on 1.x on Jakarta. This also stimulates users / appservers to update in time.

**Pull request closed without merging**
