### PR TITLE
Updates base liberty image to java 17

### PR DESCRIPTION
**Pull request by appiepollo14**

### CODE REVIEW

**Comment by appiepollo14** [comment]
Fixes https://github.com/MicroShed/microshed-testing/issues/291

**Comment by appiepollo14** [comment]
Any pair of eyes able to approve this request?

**Review by KyleAure — APPROVED** [review]

**Comment by KyleAure** [comment]
@appiepollo14 Thanks for helping out on this project.  Unfortunately we haven't had many committers to this project for the last few years so the project is in a pretty bad state.  I think before we'd be willing to do another release we'd want to get this project updated to support Jakarta applications. I had started some of that work here: https://github.com/MicroShed/microshed-testing/pull/294
But still haven't been getting clean builds.

If you are interested in collaborating more on this project let me know and we can work towards another release.

**Comment by appiepollo14** [comment]
@KyleAure 'ld to help where I can. Do you have some specific tasks I can work on? How can I reach you?

**Comment by KyleAure** [comment]
@appiepollo14 I'll put together an issue of what we'll need to do for our next release and we can work together on that issue 👍🏼

**Pull request merged**
